// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LRMvcApplication.Controllers
{
    public partial class UniverController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UniverController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CourcesList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CourcesList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateCource()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateCource);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateCource()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateCource);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteCource()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteCource);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UniverController Actions { get { return MVC.Univer; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Univer";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Univer";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string CourcesList = "CourcesList";
            public readonly string CreateCource = "CreateCource";
            public readonly string UpdateCource = "UpdateCource";
            public readonly string DeleteCource = "DeleteCource";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string CourcesList = "CourcesList";
            public const string CreateCource = "CreateCource";
            public const string UpdateCource = "UpdateCource";
            public const string DeleteCource = "DeleteCource";
        }


        static readonly ActionParamsClass_CourcesList s_params_CourcesList = new ActionParamsClass_CourcesList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CourcesList CourcesListParams { get { return s_params_CourcesList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CourcesList
        {
            public readonly string pageNumber = "pageNumber";
            public readonly string pageSize = "pageSize";
            public readonly string search = "search";
        }
        static readonly ActionParamsClass_CreateCource s_params_CreateCource = new ActionParamsClass_CreateCource();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateCource CreateCourceParams { get { return s_params_CreateCource; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateCource
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_UpdateCource s_params_UpdateCource = new ActionParamsClass_UpdateCource();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateCource UpdateCourceParams { get { return s_params_UpdateCource; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateCource
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteCource s_params_DeleteCource = new ActionParamsClass_DeleteCource();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteCource DeleteCourceParams { get { return s_params_DeleteCource; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteCource
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CourcesList = "CourcesList";
                public readonly string Index = "Index";
            }
            public readonly string CourcesList = "~/Views/Univer/CourcesList.cshtml";
            public readonly string Index = "~/Views/Univer/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UniverController : LRMvcApplication.Controllers.UniverController
    {
        public T4MVC_UniverController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CourcesListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? pageNumber, int? pageSize, string search);

        [NonAction]
        public override System.Web.Mvc.ActionResult CourcesList(int? pageNumber, int? pageSize, string search)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CourcesList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageNumber", pageNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageSize", pageSize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            CourcesListOverride(callInfo, pageNumber, pageSize, search);
            return callInfo;
        }

        [NonAction]
        partial void CreateCourceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LRMvcApplication.Models.CourceModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateCource(LRMvcApplication.Models.CourceModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateCource);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateCourceOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void UpdateCourceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LRMvcApplication.Models.CourceModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateCource(LRMvcApplication.Models.CourceModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateCource);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            UpdateCourceOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteCourceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LRMvcApplication.Models.CourceModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteCource(LRMvcApplication.Models.CourceModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteCource);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            DeleteCourceOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
